spring:
  profiles:
    active: ${YML_PROFILE:local}

---
spring:
  profiles: local
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    username: sys as SYSDBA
    password: sys
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8080